sonar.projectKey=codesync-frontend
sonar.projectName=CodeSync Frontend
sonar.projectVersion=1.0
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/assets/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.tsconfigPath=tsconfig.json
